version: '3.8'

services:
  # Nama service 
  postgres-db:
    image: postgres:latest
    container_name: nutri-track-db
    restart: always
    environment:
      # Informasi login database di dalam Docker
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=nutritrack_local
    ports:
      # Membuka port 5433 
      - '5433:5432'